SerilogElkDemo.Web/Models/ErrorViewModel.cs
using System;

namespace SerilogElkDemo.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SerilogElkDemo.Web/Models/OperationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace SerilogElkDemo.Web.Models
{
    public class OperationViewModel
    {
        [DisplayName("First Number")]
        public int FirstNumber { get; set; }
        [DisplayName("Second Number")]
        public int SecondNumber { get; set; }
        [DisplayName("Result")]
        public double? Result { get; set; }

    }
}

SerilogElkDemo.Web/Controllers/CalculatorController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Serilog;
using SerilogElkDemo.Web.Models;
using SerilogElkDemo.Web.Services;

namespace SerilogElkDemo.Web.Controllers
{
    public class CalculatorController : Controller
    {
        private readonly ICalculatorService _calculatorService;
        private readonly ILogger<CalculatorController> _logger;
        private readonly Serilog.Core.Logger _myLogger;

        public CalculatorController(ICalculatorService calculatorService,
                                    ILogger<CalculatorController> logger)
        {
            _calculatorService = calculatorService;
            _logger = logger;

        }
        public ActionResult Index()
        {
            return View(new OperationViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Add(OperationViewModel operation)
        {
            _logger.BeginScope("Wow, CalculatorController");


            _logger.LogInformation("Such action. Adding time!");
            operation.Result = await _calculatorService.Add(operation.FirstNumber, operation.SecondNumber);
            return View("Index", operation);
        }

        [HttpPost]
        public async Task<IActionResult> Sub(OperationViewModel operation)
        {
            operation.Result = await _calculatorService.Sub(operation.FirstNumber, operation.SecondNumber);
            return View("Index", operation);
        }
        [HttpPost]
        public async Task<IActionResult> Multi(OperationViewModel operation)
        {
            operation.Result = await _calculatorService.Multi(operation.FirstNumber, operation.SecondNumber);
            return View("Index", operation);
        }
        [HttpPost]
        public async Task<IActionResult> Div(OperationViewModel operation)
        {
            operation.Result = await _calculatorService.Div(operation.FirstNumber, operation.SecondNumber);
            return View("Index", operation);
        }
        [HttpPost]
        public async Task<IActionResult> RemoteMulti(OperationViewModel operation)
        {
            operation.Result = await _calculatorService.RemoteMulti(operation.FirstNumber, operation.SecondNumber);
            return View("Index", operation);
        }
        [HttpPost]
        public async Task<IActionResult> RemoteDiv(OperationViewModel operation)
        {
            operation.Result = await _calculatorService.RemoteDiv(operation.FirstNumber, operation.SecondNumber);
            return View("Index", operation);
        }

        //private AwesomeLog CreateAwesomeLog(string message)
        //{
        //    return new AwesomeLog
        //    {
        //        Message = message,
        //        Location = nameof(CalculatorController),
        //    };
        //}
        //private AwesomeLog CreateAwesomeErrorLog(string message, Exception ex)
        //{
        //    return new AwesomeLog
        //    {
        //        Message = message,
        //        Exception = ex,
        //        Location = nameof(CalculatorController),
        //    };
        //}
    }
}

SerilogElkDemo.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity.UI.V3.Pages.Internal.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Serilog;
using Serilog.Context;
using Serilog.Formatting.Json;
using SerilogElkDemo.Web.Models;

namespace SerilogElkDemo.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly Serilog.Core.Logger _myLogger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;

            _myLogger = new LoggerConfiguration()
                .WriteTo.Console()
                //.Enrich.FromLogContext()
                //.WriteTo.File(new JsonFormatter(), "log.txt", rollingInterval: RollingInterval.Day)
                .CreateLogger();
        }

        public IActionResult Index()
        {
            //ILogger
            _logger.BeginScope("User: {username}", User.Identity?.Name);
            _logger.LogInformation("Hey! I'm in the Index!");
            try
            {

                for (int i = 0; i < 10; i++)
                {
                    _logger.LogInformation("For loop... {i}", i);
                    if (i == 5)
                    {
                        throw new Exception("ups!");
                    }
                }
            }
            catch (Exception e)
            {
                _logger.LogError(e, "Strange... something broke");
            }

            //Serilog

            //LogContext.PushProperty("User", User.Identity?.Name);
            //_myLogger.Information("User: {username}", User.Identity?.Name);
            //try
            //{

            //    for (int i = 0; i < 10; i++)
            //    {
            //        _myLogger.Information("For loop... {i}", i);

            //        if (i == 5)
            //        {
            //            throw new Exception("ups!");
            //        }
            //    }
            //}
            //catch (Exception e)
            //{
            //    _myLogger.Error(e, "Strange... something broke");
            //}

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SerilogElkDemo.Web/Views/Calculator/Index.cshtml
@model SerilogElkDemo.Web.Models.OperationViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    string result = Model.Result.HasValue ? Model.Result.Value.ToString("0.####") : "";
}

<h1>Elo Calculator</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstNumber" class="control-label"></label>
                <input asp-for="FirstNumber" class="form-control" />
                <span asp-validation-for="FirstNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondNumber" class="control-label"></label>
                <input asp-for="SecondNumber" class="form-control" />
                <span asp-validation-for="SecondNumber" class="text-danger"></span>
            </div>
            <div class="form-group btn-group-vertical">
                <input type="submit" value="Add" class="btn btn-primary" formaction="/Calculator/Add" />
                <input type="submit" value="Sub" class="btn btn-secondary" formaction="/Calculator/Sub" />
                <input type="submit" value="Multi" class="btn btn-warning" formaction="/Calculator/Multi" />
                <input type="submit" value="Div" class="btn btn-danger" formaction="/Calculator/Div" />
                <input type="submit" value="RemoteMulti" class="btn btn-warning" formaction="/Calculator/RemoteMulti" />
                <input type="submit" value="RemoteDiv" class="btn btn-danger" formaction="/Calculator/RemoteDiv" />
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="card">
        <div class="card-body">
            Score: @result
        </div>
    </div>
</div>

SerilogElkDemo.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SerilogElkDemo.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SerilogElkDemo.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SerilogElkDemo.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Calculator" asp-action="Index">Calculator</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SerilogElkDemo.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>